#version: '3'

services:
  database:
    container_name: humorie_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: humorie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  redis:
    container_name: humorie_redis
    image: redis:latest
    ports:
      - '6379:6379'

  application:
    container_name: humorie
    restart: no
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SPRING_DATASOURCE_URL: jdbc:postgresql://humorie_postgres:5432/humorie_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database
      - redis
