version: '3'

services:
  database:
    container_name: humorie_postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: humorie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /mnt/postgres/data:/var/lib/postgresql/data

  redis:
    container_name: humorie_redis
    image: redis:latest
    ports:
      - '6379:6379'

  application:
    container_name: humorie
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/humorie
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database
      - redis

