spring:
  application:
    name: humorie

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/humorie
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver


  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 68ba9b63f20026c68b4513f15131a61d2821e35f5b3e322ead18f26c889dece0e90faa0c63236fa3f4db8fde1467590afe0370e9896bf03f220d473ac37a785d

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

#logging:
#  level:
#    root: DEBUG