spring:
  application:
    name: humorie

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/humorie
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver


  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

#logging:
#  level:
#    root: DEBUG